### ISSUE TITLE
Build with Go 1.27 fails

### ISSUE THREAD

**Issue by stefanb** [cockroachdb/swiss#51]
Build with Go 1.27  (rc1 & rc2)  fails with `map.go: undefined: hashFn, getRuntimeHasher, fastrand64`, as experienced in
* https://github.com/Homebrew/homebrew-core/pull/288803

Probably needs update similar to previous:
* https://github.com/cockroachdb/swiss/pull/50
* https://github.com/cockroachdb/swiss/pull/49
* https://github.com/cockroachdb/swiss/pull/43

Or some other, future proof solution that will not need to be updated with every future Go version release, since the Swiss maps are not an experimental feature anymore.

**Comment by stefanb** [comment]
Fix implemented in 
* https://github.com/cockroachdb/swiss/pull/52
