### ISSUE TITLE
Goland 1.24 version incompatibility

### ISSUE THREAD

**Issue by paulnpdev** [cockroachdb/swiss#47]
We would like to upgrade to Golang 1.24, but there's an underlying incompatibility caused by pebble's dependency on cockroachdb/swiss, which does not compile with 1.24 

The specific errors are:

# github.com/cockroachdb/swiss
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/map.go:286:7: undefined: hashFn
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/map.go:340:14: undefined: getRuntimeHasher
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/map.go:341:22: undefined: fastrand64
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/map.go:646:19: undefined: fastrand64
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/map.go:667:20: undefined: fastrand64
/Users/paul/go/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20240612210725-f4de07ae6964/options.go:30:14: undefined: hashFn

I did note that golang v1.24 actually comes with its *own* implementation of the Google Swiss hash map:
https://go.dev/blog/swisstable

So unless your port outperforms the (new) builtin version, maybe it's a switchover rather than a port/rewrite.

At any rate, really just asking whether you have a roadmap for updating your golang dependency to 1.24 for our planning purposes.

**Comment by paulnpdev** [comment]
Note that this is non-blocking for us since we can simply override in our go.mod

`replace github.com/cockroachdb/swiss => github.com/cockroachdb/swiss v0.0.0-20250327203710-0a8dbaa58e2a `

**Comment by petermattis** [comment]
> At any rate, really just asking whether you have a roadmap for updating your golang dependency to 1.24 for our planning purposes.

@paulnpdev Did you file this issue in the right place? go1.24 support was added in #43. As you note, you just need to update your dependency on github.com/cockroachdb/swiss.

**Comment by paulnpdev** [comment]
I had thought your dependency update would automatically (transitively) show up in ours, but apparently not.
